# fly.toml app configuration file generated for bun-yt-svc on 2025-08-14T08:49:32+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bun-yt-svc'
primary_region = 'sin'

[build]

[env]
  APP_PORT = '1331'

[http_service]
  internal_port = 1331
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
