import * as protobuf from "protobufjs";
import { Buffer } from "buffer";

function base64url(buf: Uint8Array): string {
  return Buffer.from(buf)
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

export function generateTranscriptParams(
  videoId: string,
  languageCode: string,
  autoGenerated: boolean,
  translateTo?: string // optional target language code
): string {
  const kind = autoGenerated ? "asr" : "";

  // Inner message (the base64 one)
  const Inner = new protobuf.Type("Inner")
    .add(new protobuf.Field("kind", 1, "string"))
    .add(new protobuf.Field("language_code", 2, "string"))
    .add(new protobuf.Field("empty", 3, "string"));

  const innerBytes = Inner.encode(
    Inner.create({
      kind,
      language_code: languageCode,
      empty: ""
    })
  ).finish();

  // Base64url encode inner
  const innerBase64 = base64url(innerBytes);

  // Outer message
  const Outer = new protobuf.Type("Outer")
    .add(new protobuf.Field("video_id", 1, "string"))
    .add(new protobuf.Field("inner_b64", 2, "string"))
    .add(new protobuf.Field("num3", 3, "int64"))
    .add(new protobuf.Field("panel", 5, "string"))
    .add(new protobuf.Field("num6", 6, "int64"))
    .add(new protobuf.Field("num7", 7, "int64"))
    .add(new protobuf.Field("num8", 8, "int64"));

  // For translation, add field 4: target_language
  if (translateTo) {
    Outer.add(new protobuf.Field("target_language", 4, "string"));
  }

  const outerPayload: any = {
    video_id: videoId,
    inner_b64: innerBase64,
    num3: 1,
    panel: "engagement-panel-searchable-transcript-search-panel",
    num6: 1,
    num7: 1,
    num8: 1
  };

  if (translateTo) {
    outerPayload.target_language = translateTo;
  }

  const outerBytes = Outer.encode(Outer.create(outerPayload)).finish();

  return base64url(outerBytes);
}

// Examples:
console.log(generateTranscriptParams("-4GmbBoYQjE", "id", true));