name: CI (Test -> Publish + Deploy)

on:
  push:
    branches: [ main ]
    tags: [ 'v*', 'release-*', '*.*.*' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Unit Tests (Bun)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run unit tests
        shell: bash
        run: |
          bun test

  docker_publish:
    name: Docker Publish (GHCR)
    needs: test
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit

  fly_deploy:
    name: Fly Deploy
    needs: test
    uses: ./.github/workflows/fly-deploy.yml
    secrets: inherit
