name: CI (Test -> Publish + Deploy)

on:
  push:
    branches: [ main ]
    tags: [ 'v*', 'release-*', '*.*.*' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Unit Tests (Bun)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run unit tests
        shell: bash
        run: |
          set -o pipefail
          bun test --serial 2>&1 | tee test.out

      - name: Summarize failures (names + reasons)
        if: failure()
        shell: bash
        run: |
          echo "::group::Failed test names"
          grep -E '^[[:space:]]*✗ ' test.out | sed 's/^[[:space:]]*✗ /- /' || echo "No failed lines found"
          echo "::endgroup::"

          echo "::group::Failure reasons"
          grep -E '::error ' test.out | sed 's/^.*title=//' || echo "No ::error annotations found"
          echo "::endgroup::"

          {
            echo "### Failed test names"
            grep -E '^[[:space:]]*✗ ' test.out | sed 's/^[[:space:]]*✗ /- /' || true
            echo
            echo "### Failure reasons"
            grep -E '::error ' test.out | sed 's/^.*title=//' || true
          } >> "$GITHUB_STEP_SUMMARY"

  docker_publish:
    name: Docker Publish (GHCR)
    needs: test
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit

  fly_deploy:
    name: Fly Deploy
    needs: test
    uses: ./.github/workflows/fly-deploy.yml
    secrets: inherit
